---
title: "S_van_Mesdag_Biodiversity_Analyses_1"
author: "Savanna van Mesdag"
date: "2023-08-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


##The following is written by Savanna van Mesdag, going through the relevant coding and analyses for the biodiversity analyses for the six anthropogenic substrate study sites.

#setwd#

#To run the following code to carry out the analyses, the following packages must be installed#

```{R}

install.packages("iNEXT", repos = 	"http://chao.stat.nthu.edu.tw/wordpress/software_download/")

install.packages('devtools', repos = "https://github.com/r-lib/devtools")

install.packages('AnneChao/iNEXT', repos = 	"http://chao.stat.nthu.edu.tw/wordpress/software_download/")

install.packages("ggthemes", repos = "https://github.com/jrnold/ggthemes")

install.packages("vegan", repos = "	https://github.com/vegandevs/vegan")

```

##The packages also need to be loaded prior to running the analyses and producing graphs#
```{R}

library(devtools)
library(iNEXT)
library(ggplot2)
library(ggthemes)
library(vegan)

```

#Loading Barrow data

```{R}
urlfile1 <- 'https://raw.githubusercontent.com/Savannankvm/Biodiversity-analyses-for-six-study-sites/PhD-files/Barrow_Abundance_Data.csv?token=GHSAT0AAAAAACG4POBNQ6K6T4V5KYG6HMXSZHOAFWQ'

Barrow_Nos <-read.csv(urlfile1)

```

#To look at the Barrow data#

```{R}
print(Barrow_Nos)

```

#colSums to establish sample size for each of the quadrats.
```{R}
colSums(Barrow_Nos)
```

#Setting m to sample size for Quadrat 1 (132 individuals.) This will give me observed
#qD value that will be most representative for Quadrat and Community. Will do the same
#for the other 10 communities below.

```{R}

m <- c(132)

Barrow_Datam <- iNEXT(Barrow_Nos, q=c(0), datatype= "abundance", size = m)

Barrow_Datam

Barrow_Datam_1 <- iNEXT(Barrow_Nos, q=c(0,1,2), datatype= "abundance", size = m)

Barrow_Datam_1

n <- c(444)

Barrow_Datan <- iNEXT(Barrow_Nos, q=c(0), datatype= "abundance", size = n)

Barrow_Datan

o <- c(446)

Barrow_Datao <- iNEXT(Barrow_Nos, q=c(0), datatype= "abundance", size = o)

Barrow_Datao

p <- c(294)

Barrow_Datap <- iNEXT(Barrow_Nos, q=c(0), datatype= "abundance", size = p)

Barrow_Datap

q <- c(277)

Barrow_Dataq <- iNEXT(Barrow_Nos, q=c(0), datatype= "abundance", size = q)

Barrow_Dataq

r <- c(464)

Barrow_Datar <- iNEXT(Barrow_Nos, q=c(0), datatype= "abundance", size = r)

Barrow_Datar

s <- c(328)

Barrow_Datas <- iNEXT(Barrow_Nos, q=c(0), datatype= "abundance", size = s)

Barrow_Datas

t <- c(428)

Barrow_Datat <- iNEXT(Barrow_Nos, q=c(0), datatype= "abundance", size = t)

Barrow_Datat

u <- c(82)

Barrow_Datau <- iNEXT(Barrow_Nos, q=c(0), datatype= "abundance", size = u)

Barrow_Datau

v <- c(250)

Barrow_Datav <- iNEXT(Barrow_Nos, q=c(0), datatype= "abundance", size = v)

Barrow_Datav

w <- c(155)

Barrow_Dataw <- iNEXT(Barrow_Nos, q=c(0), datatype= "abundance", size = w)

Barrow_Dataw

```

#Now to run the analysis again without specificying the size, can do this for
#looking at the other diversity indices#

```{R}

Barrow_Data <- iNEXT(Barrow_Nos, q=c(0), datatype= "abundance")

Barrow_Data

Barrow_Data_1 <- iNEXT(Barrow_Nos, q=c(1), datatype = "abundance")

Barrow_Data_1

```

#Now to look at further things, such as sample coverage#

```{R}

Barrowout1 <- estimateD(Barrow_Nos, q = c(0,1,2), datatype = "abundance", base="size")
Barrowout1

Barrowout2 <- estimateD(Barrow_Nos, q = c(0,1,2), datatype = "abundance", base="coverage")
Barrowout2

```

#Looking at species evenness using the vegan package#

```{R}

H <- diversity(Barrow_Nos)

Bevenness <- H/log(specnumber(Barrow_Nos))

summary(Bevenness)

H1 <- diversity(Barrow_Nos$Quadrat.1)

Bevenness1 <- H1/log(specnumber(Barrow_Nos$Quadrat.1))

summary(Bevenness1)

H2 <- diversity(Barrow_Nos$Quadrat.2)

Bevenness2 <- H2/log(specnumber(Barrow_Nos$Quadrat.2))

summary(Bevenness2)

H3 <- diversity(Barrow_Nos$Quadrat.3)

Bevenness3 <- H3/log(specnumber(Barrow_Nos$Quadrat.3))

summary(Bevenness3)

H4 <- diversity(Barrow_Nos$Quadrat.4)

Bevenness4 <- H4/log(specnumber(Barrow_Nos$Quadrat.4))

summary(Bevenness4)

H5 <- diversity(Barrow_Nos$Quadrat.5)

Bevenness5 <- H5/log(specnumber(Barrow_Nos$Quadrat.5))

summary(Bevenness5)

H6 <- diversity(Barrow_Nos$Quadrat.6)

Bevenness6 <- H6/log(specnumber(Barrow_Nos$Quadrat.6))

summary(Bevenness6)

H7 <- diversity(Barrow_Nos$Quadrat.7)

Bevenness7 <- H7/log(specnumber(Barrow_Nos$Quadrat.7))

summary(Bevenness7)

H8 <- diversity(Barrow_Nos$Quadrat.8)

Bevenness8 <- H8/log(specnumber(Barrow_Nos$Quadrat.8))

summary(Bevenness8)

H9 <- diversity(Barrow_Nos$Quadrat.9)

Bevenness9 <- H9/log(specnumber(Barrow_Nos$Quadrat.9))

summary(Bevenness9)

H10 <- diversity(Barrow_Nos$Quadrat.10)

Bevenness10 <- H10/log(specnumber(Barrow_Nos$Quadrat.10))

summary(Bevenness10)

H11 <- diversity(Barrow_Nos$Quadrat.11)

Bevenness11 <- H11/log(specnumber(Barrow_Nos$Quadrat.11))

summary(Bevenness11)

```

##Now to generate graphs to better visually examine species curves etc##

```{R}

Barrow_Data_Graph1 <- ggiNEXT(x = Barrow_Data, se=TRUE, type = 1,
                              facet.var = "None", grey=TRUE)

Barrow_Data_Graph1


g7 <- Barrow_Data_Graph1 + theme_hc(style = "darkunica") +
  scale_colour_hc("darkunica")

g7


Barrow_Data_Graph2 <- ggiNEXT(x = Barrow_Data, se=TRUE, type = 1,
                              facet.var="None", grey= TRUE) 

Barrow_Data_Graph2

plot(Barrow_Data, type=1)

Barrow_Data_Graph3 <- ggiNEXT(x = Barrow_Data, se=TRUE, type = 2,
                              facet.var="None", grey = TRUE) 

Barrow_Data_Graph3

plot(Barrow_Data, type=2)

Barrow_Data_Graph4 <- ggiNEXT(x = Barrow_Data, se=TRUE, type = 3,
                              facet.var="None", grey= TRUE) 
Barrow_Data_Graph4

plot(Barrow_Data, type=3)

```
##Fallin Data##

```{R}

urlfile2 <- 'https://raw.githubusercontent.com/Savannankvm/Biodiversity-analyses-for-six-study-sites/PhD-files/Fallin_Abundance_Data.csv'

Fallin_Nos <-read.csv(urlfile2)

print(Fallin_Nos)

```

#colSums to establish sample size for each of the quadrats.

```{R}

colSums(Fallin_Nos)

```

#Setting m to sample size for Quadrat 1. This will give me observed
#qD value that will be most representative for Quadrat and Community. Will do the same
#for the other communities below.

```{R}

m <- c(711)

Fallin_Datam <- iNEXT(Fallin_Nos, q=c(0), datatype= "abundance", size = m)

Fallin_Datam

n <- c(525)

Fallin_Datan <- iNEXT(Fallin_Nos, q=c(0), datatype= "abundance", size = n)

Fallin_Datan

o <- c(639)

Fallin_Datao <- iNEXT(Fallin_Nos, q=c(0), datatype= "abundance", size = o)

Fallin_Datao

p <- c(820)

Fallin_Datap <- iNEXT(Fallin_Nos, q=c(0), datatype= "abundance", size = p)

Fallin_Datap

q <- c(798)

Fallin_Dataq <- iNEXT(Fallin_Nos, q=c(0), datatype= "abundance", size = q)

Fallin_Dataq

```


#Now to run the analysis again for Fallin without specificying the size, can do this for
#looking at the other diversity indices

```{R}

Fallin_Data <- iNEXT(Fallin_Nos, q=c(0), datatype= "abundance")

Fallin_Data

F1 <- diversity(Fallin_Nos$Quadrat_1)

```

#Now to do other analyses to generate further biodiversity indices for Fallin, including coverage

```{R}

Fallin2 <- estimateD(Fallin_Nos, q = c(0,1,2), datatype = "abundance", base="coverage")
Fallin2

```

#Now to do vegan analyses for species evenness for Fallin data

```{R}

Fevenness1 <- F1/log(specnumber(Fallin_Nos$Quadrat_1))

summary(Fevenness1)

F2 <- diversity(Fallin_Nos$Quadrat_2)

Fevenness2 <- F2/log(specnumber(Fallin_Nos$Quadrat_2))

summary(Fevenness2)

F3 <- diversity(Fallin_Nos$Quadrat_3)

Fevenness3 <- F3/log(specnumber(Fallin_Nos$Quadrat_3))

summary(Fevenness3)

F4 <- diversity(Fallin_Nos$Quadrat_4)

Fevenness4 <- F4/log(specnumber(Fallin_Nos$Quadrat_4))

summary(Fevenness4)

F5 <- diversity(Fallin_Nos$Quadrat_5)

Fevenness5 <- F5/log(specnumber(Fallin_Nos$Quadrat_5))

summary(Fevenness5)

```

#Now to generate some graphs for Fallin data for better visualisation, including to visualise species curves#

```{R}

Fallin_Data_Graph1 <- ggiNEXT(x = Fallin_Data, se=TRUE, color.var="Order.q")

Fallin_Data_Graph1

Fallin_Data_Graph1.1 <- ggiNEXT(x = Fallin_Data, se=TRUE, type = 1,
                                facet.var="None", grey=TRUE)

Fallin_Data_Graph1.1

Falling <- Fallin_Data_Graph1.1 + theme_hc(style = "darkunica") +
  scale_colour_hc("darkunica")

Falling

Fallin_Data_Graph2 <- ggiNEXT(x = Fallin_Data, se=TRUE, type = 1,
                              facet.var="None", grey=TRUE)

Fallin_Data_Graph2

Fallin_Data_Graph3 <- ggiNEXT(x = Fallin_Data, se=TRUE, type = 2,
                              facet.var="None", grey=TRUE)

Fallin_Data_Graph3

Falling3 <- Fallin_Data_Graph3 + theme_hc(style = "darkunica") +
  scale_colour_hc("darkunica")

Falling3

Fallin_Data_Graph4 <- ggiNEXT(x = Fallin_Data, se=TRUE, type = 3,
                              facet.var="None", grey=TRUE)

Fallin_Data_Graph4

Falling4 <- Fallin_Data_Graph4 + theme_hc(style = "darkunica") +
  scale_colour_hc("darkunica")

Falling4

```


##Addiewell Data##

##Loading the Addiewell data##

```{R}

urlfile3 <- 'https://raw.githubusercontent.com/Savannankvm/Biodiversity-analyses-for-six-study-sites/PhD-files/Addiewell_Abundance_Data.csv'

Addiewell_Nos <-read.csv(urlfile3)

print(Addiewell_Nos)

```


#colSums to establish sample size for each of the quadrats.

```{R}

colSums(Addiewell_Nos)

```

#Setting m to sample size for Quadrat 1. This will give me observed
#qD value that will be most representative for Quadrat and Community. Will do the same
#for the other communities below.

```{R}

m <- c(420)

Addiewell_Datam <- iNEXT(Addiewell_Nos, q=c(0), datatype= "abundance", size = m)

Addiewell_Datam

n <- c(533)

Addiewell_Datan <- iNEXT(Addiewell_Nos, q=c(0), datatype= "abundance", size = n)

Addiewell_Datan

o <- c(621)

Addiewell_Datao <- iNEXT(Addiewell_Nos, q=c(0), datatype= "abundance", size = o)

Addiewell_Datao

p <- c(824)

Addiewell_Datap <- iNEXT(Addiewell_Nos, q=c(0), datatype= "abundance", size = p)

Addiewell_Datap

q <- c(395)

Addiewell_Dataq <- iNEXT(Addiewell_Nos, q=c(0), datatype= "abundance", size = q)

Addiewell_Dataq

```

#Now to run the analysis again without specificying the size, can do this for
#looking at the other diversity indices

```{R}

Addiewell_Data <- iNEXT(Addiewell_Nos, q=c(0), datatype= "abundance")

print(Addiewell_Data)

```

##Now to do further analyses for initial biodiversity indices for Addiewell, including sample coverage

```{R}


A1 <- diversity(Addiewell_Nos$Quadrat.1)

Addiewell2 <- estimateD(Addiewell_Nos, q = c(0,1,2), datatype = "abundance", base="coverage")
Addiewell2

```

#Running vegan analyses for species evenness for Addiewell data#

```{R}

Aevenness1 <- A1/log(specnumber(Addiewell_Nos$Quadrat.1))

summary(Aevenness1)

A2 <- diversity(Addiewell_Nos$Quadrat.2)

Aevenness2 <- A2/log(specnumber(Addiewell_Nos$Quadrat.2))

summary(Aevenness2)

A3 <- diversity(Addiewell_Nos$Quadrat.3)

Aevenness3 <- A3/log(specnumber(Addiewell_Nos$Quadrat.3))

summary(Aevenness3)

A4 <- diversity(Addiewell_Nos$Quadrat.4)

Aevenness4 <- A4/log(specnumber(Addiewell_Nos$Quadrat.4))

summary(Aevenness4)

A5 <- diversity(Addiewell_Nos$Quadrat.5)

Aevenness5 <- A5/log(specnumber(Addiewell_Nos$Quadrat.5))

summary(Aevenness5)

```

#Now to create some graphs for better visualisation of the data, including species curves#

```{R}

Addiewell_Data_Graph1 <- ggiNEXT(x = Addiewell_Data, se=TRUE, color.var="Order.q")

Addiewell_Data_Graph1

Addiewell_Data_Graph1.1 <- ggiNEXT(x = Addiewell_Data, se=TRUE,
                                   facet.var = "None", grey=TRUE)

Addiewell_Data_Graph1.1

Addiewell_Data_Graph2 <- ggiNEXT(x = Addiewell_Data, se=TRUE, type = 1,
                                 facet.var = "None", grey=TRUE)

Addiewell_Data_Graph2

Addiewellg2 <- Addiewell_Data_Graph2 + theme_hc(style = "darkunica") +
  scale_colour_hc("darkunica")

Addiewellg2

Addiewell_Data_Graph2.1 <- ggiNEXT(x = Addiewell_Data, se=TRUE, type = 1,
                                   facet.var="None", grey=TRUE) 

Addiewell_Data_Graph2.1

Addiewell_Data_Graph3 <- ggiNEXT(x = Addiewell_Data, se=TRUE, type = 2,
                                 facet.var="None", grey = TRUE) 

Addiewell_Data_Graph3

Addiewell_Data_Graph4 <- ggiNEXT(x = Addiewell_Data, se=TRUE, type = 3,
                                 facet.var="None", grey = TRUE) 

Addiewell_Data_Graph4

```


#Hodbarrow Data#

#Loading the Hodbarrow data#

```{R}

urlfile4 <- 'https://raw.githubusercontent.com/Savannankvm/Biodiversity-analyses-for-six-study-sites/PhD-files/Hodbarrow_Abundance_Data.csv'

Hodbarrow_Nos <-read.csv(urlfile4)

print(Hodbarrow_Nos)

```

#colSums to establish sample size for each of the quadrats.

```{R}

colSums(Hodbarrow_Nos)

```

#Setting m to sample size for Quadrat 1. This will give me observed
#qD value that will be most representative for Quadrat and Community. Will do the same
#for the other communities below.

```{R}

m <- c(213)

Hodbarrow_Datam <- iNEXT(Hodbarrow_Nos, q=c(0), datatype= "abundance", size = m)

Hodbarrow_Datam

n <- c(396)

Hodbarrow_Datan <- iNEXT(Hodbarrow_Nos, q=c(0), datatype= "abundance", size = n)

Hodbarrow_Datan

o <- c(617)

Hodbarrow_Datao <- iNEXT(Hodbarrow_Nos, q=c(0), datatype= "abundance", size = o)

Hodbarrow_Datao

p <- c(577)

Hodbarrow_Datap <- iNEXT(Hodbarrow_Nos, q=c(0), datatype= "abundance", size = p)

Hodbarrow_Datap

q <- c(433)

Hodbarrow_Dataq <- iNEXT(Hodbarrow_Nos, q=c(0), datatype= "abundance", size = q)

Hodbarrow_Dataq

r <- c(106)

Hodbarrow_Datar <- iNEXT(Hodbarrow_Nos, q=c(0), datatype= "abundance", size = r)

Hodbarrow_Datar

s <- c(216)

Hodbarrow_Datas <- iNEXT(Hodbarrow_Nos, q=c(0), datatype= "abundance", size = s)

Hodbarrow_Datas

```


#Now to run the analysis again without specificying the size, can do this for
#looking at the other diversity indices

```{R}

Hodbarrow_Data <- iNEXT(Hodbarrow_Nos, q=c(0), datatype= "abundance")

print(Hodbarrow_Data)

```

#Running further analyses to obtain additional biodiversity indices, including sample coverage#

```{R}

Hodbarrow2 <- estimateD(Hodbarrow_Nos, q = c(0,1,2), datatype = "abundance", base="coverage")
Hodbarrow2

```

#Running vegan analyses for Hodbarrow, to obtain species evenness indices

```{R}

R1 <- diversity(Hodbarrow_Nos$Quadrat_1)

Revenness1 <- R1/log(specnumber(Hodbarrow_Nos$Quadrat_1))

summary(Revenness1)

R2 <- diversity(Hodbarrow_Nos$Quadrat_2)

Revenness2 <- R2/log(specnumber(Hodbarrow_Nos$Quadrat_2))

summary(Revenness2)

R3 <- diversity(Hodbarrow_Nos$Quadrat_3)

Revenness3 <- R3/log(specnumber(Hodbarrow_Nos$Quadrat_3))

summary(Revenness3)

R4 <- diversity(Hodbarrow_Nos$Quadrat_4)

Revenness4 <- R4/log(specnumber(Hodbarrow_Nos$Quadrat_4))

summary(Revenness4)

R5 <- diversity(Hodbarrow_Nos$Quadrat_5)

Revenness5 <- R5/log(specnumber(Hodbarrow_Nos$Quadrat_5))

summary(Revenness5)

R6 <- diversity(Hodbarrow_Nos$Quadrat_6)

Revenness6 <- R6/log(specnumber(Hodbarrow_Nos$Quadrat_6))

summary(Revenness6)

R7 <- diversity(Hodbarrow_Nos$Quadrat_7)

Revenness7 <- R7/log(specnumber(Hodbarrow_Nos$Quadrat_7))

summary(Revenness7)

```

#Now for some data visualisation for the Hodbarrow data, including species curves graphs#

```{R}

Hodbarrow_Data_Graph1 <- ggiNEXT(x = Hodbarrow_Data, se=TRUE, 
                                 facet.var= "None", grey=TRUE)

Hodbarrow_Data_Graph1

Hodbarrow_Data_Graph2 <- ggiNEXT(x = Hodbarrow_Data, se=TRUE, type = 1,
                                 facet.var= "None", grey=TRUE)

Hodbarrow_Data_Graph2

Hodbarrow_Data_Graph3 <- ggiNEXT(x = Hodbarrow_Data, se=TRUE, type = 2,
                                 facet.var= "None", grey=TRUE)

Hodbarrow_Data_Graph3

Hodbarrow_Data_Graph4 <- ggiNEXT(x = Hodbarrow_Data, se=TRUE, type = 3,
                                 facet.var= "None", grey=TRUE)

Hodbarrow_Data_Graph4

```

#Warton#

#Loading the Warton data

```{R}

urlfile5 <- 'https://raw.githubusercontent.com/Savannankvm/Biodiversity-analyses-for-six-study-sites/PhD-files/Warton_Abundance_Data.csv'

Warton_Nos <-read.csv(urlfile5)

print(Warton_Nos)

```

#colSums to establish sample size for each of the quadrats.

```{R}

colSums(Warton_Nos)

```

#Setting m to sample size for Quadrat 1. This will give me observed
#qD value that will be most representative for Quadrat and Community. Will do the same
#for the other communities below.

```{R}

m <- c(795)

Warton_Datam <- iNEXT(Warton_Nos, q=c(0), datatype= "abundance", size = m)

Warton_Datam

n <- c(568)

Warton_Datan <- iNEXT(Warton_Nos, q=c(0), datatype= "abundance", size = n)

Warton_Datan

o <- c(552)

Warton_Datao <- iNEXT(Warton_Nos, q=c(0), datatype= "abundance", size = o)

Warton_Datao

p <- c(322)

Warton_Datap <- iNEXT(Warton_Nos, q=c(0), datatype= "abundance", size = p)

Warton_Datap

q <- c(517)

Warton_Dataq <- iNEXT(Warton_Nos, q=c(0), datatype= "abundance", size = q)

Warton_Dataq

r <- c(206)

Warton_Datar <- iNEXT(Warton_Nos, q=c(0), datatype= "abundance", size = r)

Warton_Datar

s <- c(319)

Warton_Datas <- iNEXT(Warton_Nos, q=c(0), datatype= "abundance", size = s)

Warton_Datas

t <- c(343)

Warton_Datat <- iNEXT(Warton_Nos, q=c(0), datatype= "abundance", size = t)

Warton_Datat

```


#Now to run the analysis again without specificying the size, can do this for
#looking at the other diversity indices

```{R}

Warton_Data <- iNEXT(Warton_Nos, q=c(0), datatype= "abundance")

print(Warton_Data)

summary(Warton_Data)

```

#Now to obtain additional biodiversity indices for the Warton data, including sample coverage#

```{R}

W1 <- diversity(Warton_Nos$Quadrat_1)

Warton2 <- estimateD(Warton_Nos, q = c(0,1,2), datatype = "abundance", base="coverage")
Warton2

Wevenness1 <- W1/log(specnumber(Warton_Nos$Quadrat_1))

summary(Wevenness1)

W2 <- diversity(Warton_Nos$Quadrat_2)

Wevenness2 <- W2/log(specnumber(Warton_Nos$Quadrat_2))

summary(Wevenness2)

W3 <- diversity(Warton_Nos$Quadrat_3)

Wevenness3 <- W3/log(specnumber(Warton_Nos$Quadrat_3))

summary(Wevenness3)

W4 <- diversity(Warton_Nos$Quadrat_4)

Wevenness4 <- W4/log(specnumber(Warton_Nos$Quadrat_4))

summary(Wevenness4)

W5 <- diversity(Warton_Nos$Quadrat_5)

Wevenness5 <- W5/log(specnumber(Warton_Nos$Quadrat_5))

summary(Wevenness5)

W6 <- diversity(Warton_Nos$Quadrat_6)

Wevenness6 <- W6/log(specnumber(Warton_Nos$Quadrat_6))

summary(Wevenness6)

W7 <- diversity(Warton_Nos$Quadrat_7)

Wevenness7 <- W7/log(specnumber(Warton_Nos$Quadrat_7))

summary(Wevenness7)

W8 <-diversity(Warton_Nos$Quadrat_8)

Wevenness8 <-W8/log(specnumber(Warton_Nos$Quadrat_8))

summary(Wevenness8)

```

#Now for Warton data visualisation, including species curve visualisation#

```{R}

Warton_Data_Graph1 <- ggiNEXT(x = Warton_Data, se=TRUE, color.var="Order.q")

Warton_Data_Graph1

Warton_Data_Graph2 <- ggiNEXT(x = Warton_Data, se=TRUE, type = 1,
                              facet.var="None", color.var="Order.q") 

Warton_Data_Graph2

Warton_Data_Graph3 <- ggiNEXT(x = Warton_Data, se=TRUE, type = 2,
                              facet.var="None", color.var="Order.q") 

Warton_Data_Graph3

Warton_Data_Graph4 <- ggiNEXT(x = Warton_Data, se=TRUE, type = 3,
                              facet.var="None", color.var="Order.q") 

Warton_Data_Graph4

```

##Penicuik##

##Loading Penicuik Data#

```{R}

urlfile5 <- 'https://raw.githubusercontent.com/Savannankvm/Biodiversity-analyses-for-six-study-sites/PhD-files/Penicuik_Abundance_Data.csv'

Penicuik_Nos <-read.csv(urlfile5)

print(Penicuik_Nos)

```

#colSums to establish sample size for each of the quadrats.

```{R}

colSums(Penicuik_Nos)

```

#Setting m to sample size for Quadrat 1. This will give me observed
#qD value that will be most representative for Quadrat and Community. Will do the same
#for the other communities below.

```{R}

m <- c(76)

Penicuik_Datam <- iNEXT(Penicuik_Nos, q=c(0), datatype= "abundance", size = m)

Penicuik_Datam

n <- c(299)

Penicuik_Datan <- iNEXT(Penicuik_Nos, q=c(0), datatype= "abundance", size = n)

Penicuik_Datan

o <- c(319)

Penicuik_Datao <- iNEXT(Penicuik_Nos, q=c(0), datatype= "abundance", size = o)

Penicuik_Datao

p <- c(324)

Penicuik_Datap <- iNEXT(Penicuik_Nos, q=c(0), datatype= "abundance", size = p)

Penicuik_Datap

q <- c(110)

Penicuik_Dataq <- iNEXT(Penicuik_Nos, q=c(0), datatype= "abundance", size = q)

Penicuik_Dataq

```

#Now to run the analysis again without specificying the size, can do this for
#looking at the other diversity indices

```{R}

Penicuik_Data <- iNEXT(Penicuik_Nos, q=c(0), datatype= "abundance")

print(Penicuik_Data)

summary(Penicuik_Data)

```

#Now to do obtain additional biodiversity indices, including sample coverage, for Penicuik#

```{R}

P1 <- diversity(Penicuik_Nos$Quadrat_1)

Penicuik2 <- estimateD(Penicuik_Nos, q = c(0,1,2), datatype = "abundance", base="coverage")
Penicuik2

```

#Now for vegan analyses to determine species eveness for Penicuik data

```{R}

Pevenness1 <- P1/log(specnumber(Penicuik_Nos$Quadrat_1))

summary(Pevenness1)

P2 <- diversity(Penicuik_Nos$Quadrat_2)

Pevenness2 <- P2/log(specnumber(Penicuik_Nos$Quadrat_2))

summary(Pevenness2)

P3 <- diversity(Penicuik_Nos$Quadrat_3)

Pevenness3 <- P3/log(specnumber(Penicuik_Nos$Quadrat_3))

summary(Pevenness3)

P4 <- diversity(Penicuik_Nos$Quadrat_4)

Pevenness4 <- P4/log(specnumber(Penicuik_Nos$Quadrat_4))

summary(Pevenness4)

P5 <- diversity(Penicuik_Nos$Quadrat_5)

Pevenness5 <- P5/log(specnumber(Penicuik_Nos$Quadrat_5))

summary(Pevenness5)

```

#Now for data visualisation for Penicuik data, including the generation of species curve graphs#

```{R}

Penicuik_Data_Graph1 <- ggiNEXT(x = Penicuik_Data, se=TRUE, color.var="Order.q")

Penicuik_Data_Graph1

Penicuik_Data_Graph2 <- ggiNEXT(x = Penicuik_Data, se=TRUE, type = 1,
                                facet.var="None", color.var="Order.q") 

Penicuik_Data_Graph2

Penicuik_Data_Graph3 <- ggiNEXT(x = Penicuik_Data, se=TRUE, type = 2,
                                facet.var="None", color.var="Order.q") 

Penicuik_Data_Graph3

Penicuik_Data_Graph4 <- ggiNEXT(x = Penicuik_Data, se=TRUE, type = 3,
                                facet.var="None", color.var="Order.q") 

Penicuik_Data_Graph4

```
